### ISSUE TITLE
EOF not handled in getline()

### ISSUE THREAD

**Issue by harishankarv** [brenns10/lsh#14]
I did not know where else to raise an issue regarding the blog post, as `getline` is not there in the code on github. Apologies for raising it here if it is not appropriate. 

The code on the blog post does not handle the case where the user inputs an EOF, wanting to exit the shell. I believe it should be:

```
char *lsh_read_line(void)
{
  char *line = NULL;
  ssize_t bufsize = 0;  // have getline allocate a buffer for us
  if (getline(&line, &bufsize, stdin) == -1)
    exit(EXIT_SUCCESS);
  return line;
}
```

Or, to be even more pedantic:

```
char *lsh_read_line(void)
{
  char *line = NULL;
  ssize_t bufsize = 0;  // have getline allocate a buffer for us

  if (getline(&line, &bufsize, stdin) == -1){
    if (feof(stdin)) {  
      exit(EXIT_SUCCESS);  // We recieved an EOF
    } else  {
      perror("readline");
      exit(EXIT_FAILURE);
    }
  }
  return line;
}
```

**Comment by brenns10** [comment]
Hi @harishankarv nice find! You're totally right. The code also wasn't even present in this repository, but I think it should be, so I added it (preserving the bug) in 5bd70fb. Since you found the bug and reported a fully correct fix, if you'd like to do the honors of submitting the pull request to fix it, you're welcome to do so! That way you get the credit in the commit log :)

I'll also go ahead and update the blog post.

**Comment by brenns10** [comment]
I like your "pedantic" version correct because it reports the correct exit code, so if you do submit the PR, please include that version!

**Comment by harishankarv** [comment]
Submitted a PR, glad I could help in some small way :)

**Comment by brenns10** [comment]
Thank you again for catching the issue, and for the fix!

**Comment by abbyrjones72** [comment]
Learning a lot from this tutorial in 2021!

**Comment by Davidlred** [comment]
Thank you guys. Learning a lot

**Comment by Bonsrah** [comment]
2025 and this tutorial is still very helpful.
Thank you
