### ISSUE TITLE
Contribution to the repository

### ISSUE THREAD

**Issue by fernandoeqc** [brenns10/lsh#18]
Hi! Is this project open to contribution?
He never contributes no projects in github, but he caught my attention, it would be a good challenge for me. If you want help, I'm at your disposal.

**Comment by brenns10** [comment]
Hi @fernandoeqc, you're welcome to fork this code and explore adding new capabilities to the shell. However, since the code here is really just for a tutorial, I don't take contributions. That way, everyone has the same starting point to explore and learn. (That said, if you find a bug and fix it, I'm happy to look at that and take the fix.)

Here's a list of suggestions for things you might want to learn and add for yourself:

- New builtin commands: pwd, alias, pushd, popd
- Backslash escaping and quote support
- Piping (eg `echo hello world | wc -w`) and redirection (eg `grep int main.c > integers.txt`)
- Support for setting variables and expanding variables in command lines (e.g. `echo $USER`)
